### ISSUE TITLE
AddModuleScore gives very different results

### ISSUE THREAD

**Issue by aj088** [carmonalab/UCell#18]
Hi,

I am using AddModuleScore to calculate the signature scoring of my single-cell data. I used GSEA gene sets as markers and followed the tutorial. My code is similar to 

pbmc.Tcell <- AddModuleScore_UCell(pbmc.Tcell, features = markers).

However, the AddModuleScore_UCell function gives a very different result of a particular gene signature. For example, I want to calculate Ucell for a particular gene set A. If I use only gene set A as input for features vs using 20 different gene sets including gene set A as input for features, the Ucell for gene set A can be completely different. Is there a reason why this function gives different results depending on numbers of gene sets? Thanks!

**Comment by mass-a** [comment]
Hello and thanks for reaching out.

I have not seen this before – would you be able to share a reproducible example of this behavior?

Best
-m

**Comment by aj088** [comment]
I am unable to share the original data. I can show some results generated by calculating Ucell scores inputting only one gene signature and Ucell scores inputting a list of gene signatures. 

The first table is generated using the AddModuleScore function for each hallmark pathway, this is my code:
seurat_v1 <- seurat
for (i in c(1:length(hallmark_pathways))){
  print(names(hallmark_pathways[i]))
  seurat_v1 <- AddModuleScore_UCell(seurat_v1, features = hallmark_pathways[i])
}
![Screen Shot 2022-03-29 at 3 35 30 PM](https://user-images.githubusercontent.com/55105250/160693311-baa1ddab-44be-40e7-94bc-29ae61b82dfd.png)

The second table is generated using the AddModuleScore function for all hallmark pathway, below my code:
seurat_v2 <- AddModuleScore_UCell(seurat, features = hallmark_pathways)
![Screen Shot 2022-03-29 at 3 35 36 PM](https://user-images.githubusercontent.com/55105250/160693324-600e48e8-d31d-4f99-afa8-caa293fed190.png)

I previously expect Ucell works at single-cell level for each gene signature, and the number of gene signature features should not affect the Ucell score. However, the results are completely different. I wonder where that difference comes from? And what is the best way to generate Ucell for pre-defined gene signatures in my case? Thank you.

**Comment by mass-a** [comment]
Hello again,

I applied your code and MSigDB signatures to a different dataset, and the results are identical whether you calculate UCell scores simultaneously or one by one. Which makes me suspect that this is specific to your dataset.

Can you confirm that you do not alter the seurat object between runs (e.g. size of the matrices, default assays etc.)? what package versions are you using? I am happy to help you further, but you are going to have to share a reproducible example (in [private](mailto:massimo.andreatta@unil.ch) if you wish).

That said, the optimal way of using UCell is to evaluate all the signatures at once. This way the gene rankings are calculated only once, instead of needlessly recalculating them for each signature.

Best
-m

**Comment by aj088** [comment]
Hello, I double-checked my code and confirm that I did not alter Seurat object. Can I share my data and code with your email? And is it It would be really nice if you can help take a look. Thank you very much for the help
