### ISSUE TITLE
Scoring down-regulated genes in signatures

### ISSUE THREAD

**Issue by reberya** [carmonalab/UCell#3]
Hello,

First of all would like to say that it has been great ot using Ucell so far. It's implementation is very straightforward and it has nice functionality.

My question relates to the use of down regulated genes. Would you recommend incorporation of these into the gene signatures or not? Other programs I've used like [singscore](https://www.bioconductor.org/packages/release/bioc/html/singscore.html) which applies to bulk RNA-seq allows the user to specificy up and down regulated genes. But from reading your biorxiv paper I didn't see any indication in regards to this. From my interpretation on how the program works it seems like the sigantures should only be upregulated. If this is the case I think it would be a nice feature to incorporate if possible for added functionality.

Thanks again,
Ryan

**Comment by mass-a** [comment]
Thanks for the suggestion!
we are indeed working on implementing signatures with up- and down-regulated genes. It should be available soon, I'll post again here when the update is ready.
Cheers,
-m

**Comment by mass-a** [comment]
You can already try the new functionalities by installing the development version:
```
remotes::install_github("carmonalab/UCell", ref="dev")
```

You can simply provide positive and negative gene sets by adding a + or - suffix to the genes, e.g.:
```
gamma_delta <- c("TRDC+", "TRGC1+", "TRGC2+", "TRDV1+","TRAC-","TRBC1-","TRBC2-")
```
otherwise everything works as before. I added some short explanation to the new scoring in the README.md (in the 'dev' branch).

Any feedback is welcome!
